name: Daily build

# Controls when the action will run.
on: 
  schedule:
    - cron: '30 2 * * *'

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Ballerina Build
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      pack
            - name: Ballerina Test
              uses: ballerina-platform/ballerina-action/@nightly
              with:
                  args:
                      test --code-coverage
              env:
                  ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
                  SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
                  REGION: ${{ secrets.REGION }}

            # Read the ballerina test results
            - name: Read Ballerina Test Results
              id: test_results
              run: |
                content=`cat ./target/report/test_results.json`                
                content="${content//'%'/'%25'}"
                content="${content//$'\n'/'%0A'}"
                content="${content//$'\r'/'%0D'}"
                echo "::set-output name=testResultsJson::$content"

            # Print the code coverage information
            - name: Code Coverage
              run: |
                echo "Code Coverage Percentage : ${{fromJson(steps.test_results.outputs.testResultsJson).coveragePercentage}}"

            # Send notification when build fails
            - name: Notify failure
              if: ${{ failure() }}
              run: |
                curl -X POST \
                'https://api.github.com/repos/ballerina-platform/ballerina-release/dispatches' \
                -H 'Accept: application/vnd.github.v3+json' \
                -H 'Authorization: Bearer ${{ secrets.BALLERINA_BOT_TOKEN }}' \
                --data "{
                  \"event_type\": \"notify-build-failure\",
                  \"client_payload\": {
                    \"repoName\": \"module-ballerinax-aws.simpledb\"
                  }
                }"
                